add authorization
iSharovatov1/NewsSiteBack pull request #4
Opened 2022-07-25 12:29 UTC by iSharovatov1

# [NewsSiteBack](https://github.com/iSharovatov1/NewsSiteBack)
> Implementation of authorization (server)
### Code Details
* added authorization
### Feature tag selection
Has a `Implementation of authorization (server )` Has it been added [to the tracker](https://trello.com/b/EICN697S/%D1%88%D0%B0%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D0%BE%D0%B2%D0%B8%D0%B3%D0%BE%D1%80%D1%8C%D0%BD%D0%BE%D0%B2%D0%BE%D1%81%D1%82%D0%BD%D0%BE%D0%B9%D1%81%D0%B0%D0%B9%D1%82)?

2022-07-25 12:41 UTC, tatiana-dunice requested changes

2022-07-25 12:41 UTC, tatiana-dunice commented on controllers/auth/signin.js
> +  const { email, password } = req.body;
const {body:{email, password}} = req;

2022-07-25 12:41 UTC, tatiana-dunice commented on controllers/auth/signin.js
> +    return res.status(400).send({ msg: 'Please pass email and password.' });
`Missed data` or `Email and password required`

2022-07-25 12:41 UTC, tatiana-dunice commented on controllers/auth/signin.js
> +  if (!email || !password) {
check trimmed values with `''`

2022-07-25 12:41 UTC, tatiana-dunice commented on controllers/auth/signin.js
> +    bcrypt.compare(password, user.password, async (err, resp) => {
move this check to user prototype

2022-07-25 12:41 UTC, tatiana-dunice commented on controllers/auth/signin.js
> +    bcrypt.compare(password, user.password, async (err, resp) => {
follow async/await syntax

2022-07-25 12:41 UTC, tatiana-dunice commented on controllers/auth/signin.js
> +        const tokens = await Tokens.findAll({ where: { userId: user.id } });
you can destroy tokens on logout
or by cron job

2022-07-25 12:41 UTC, tatiana-dunice commented on controllers/auth/signin.js
> +        return res.json({ success: true, token });
return user as well

2022-07-25 12:41 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +  if (!email || !password) {
the rest of field shouldn't be validated?  - fix it

2022-07-25 12:41 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +    const oldUser = await Users.findAll({ where: { email } });
findOne

2022-07-25 12:41 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +    const hashPassword = bcrypt.hashSync(password, bcrypt.genSaltSync(10), null);
move this to beforeCreate model hook

2022-07-25 12:41 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +    return res.status(201).cookie('token', refresh).send({ token });
send user as well

2022-07-26 07:04 UTC, tatiana-dunice requested changes

2022-07-26 07:04 UTC, tatiana-dunice commented on controllers/auth/logout.js
> +    await Tokens.destroy({ where: { token } });
You should remove cookies as well - you mostly use cookies to check if user aauthorized

2022-07-26 07:04 UTC, tatiana-dunice commented on controllers/auth/logout.js
> +    return res.json({ success: true, token });
missed status

2022-07-26 07:04 UTC, tatiana-dunice commented on controllers/auth/signin.js
>  require('dotenv').config();
move `require('dotenv').config();` to app.js

2022-07-26 07:04 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +  if (email === '' || password === '' || firstName === '' || lastName === '') {
You need to trim values

2022-07-26 07:04 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +    return res.status(201).cookie('token', refresh).send({ token, user });
Why don't you set cookies when user signup?

2022-07-26 09:56 UTC, tatiana-dunice requested changes

2022-07-26 09:56 UTC, tatiana-dunice commented on controllers/auth/logout.js
> +    return res.status(200).json({ success: true, refreshToken });
Do you really need to send removed refreshToken to user?

2022-07-26 09:56 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +  if (email.trim() === '' || password.trim() === '' || firstName.trim() === '' || lastName.trim() === '') {
split into several lines - it's hard to follow this condition

2022-07-26 09:56 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +    return res.status(400).send({ msg: 'Missed data.' });
You need to check that email is really email - not a random string - you can use regexp for that

2022-07-26 09:56 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +      firstName,
you trimed values, but put original strings to create function - fix it

2022-07-26 09:56 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +  if (oldUser) res.status(409).send('user already exists');
wrap code for this condition in `{}` brackets and `return res....`

2022-07-26 09:56 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +  const hashPassword = bcrypt.hashSync(password, bcrypt.genSaltSync(10), null);
use beforeCreate hook for user model for that

2022-07-26 09:56 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +    const token = jwt.sign(JSON.parse(JSON.stringify(user)), key, { expiresIn: 86400 * 30 });
```
const token = jwt.sign(JSON.parse(JSON.stringify(user)), key, { expiresIn: 86400 * 30 });
    const refresh = randtoken.uid(255);
    await Tokens.create({
      userId: user.id,
      token: refresh,
    });
    res.cookie('refreshToken', refresh, {
      secure: false,
      maxAge: 60 * 60 * 1000,
      httpOnly: true,
    });
    return res.status(201).cookie('token', refresh).send({ token, user });
    ```
    this is a code duplication - move to new function

2022-07-26 09:56 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +    return res.status(201).cookie('token', refresh).send({ token, user });
`.cookie` is redundant - you've already set it on the 39th line

2022-07-29 07:16 UTC, tatiana-dunice requested changes

2022-07-29 07:16 UTC, tatiana-dunice commented on db/models/users.js
> +      user.password = bcrypt.hashSync(user.password, bcrypt.genSaltSync(10), null);
what would be happen if user didn't pass password?

2022-07-29 07:16 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +    const token = jwt.sign(JSON.parse(JSON.stringify(user)), key, { expiresIn: 86400 * 30 });
this is a code duplication - move to new function

2022-07-29 07:16 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +  if (email.trim() === ''
reformat the code

2022-07-29 07:16 UTC, tatiana-dunice commented on controllers/auth/signin.js
> +  if (email === '' || password === '') {
trim email

2022-07-29 07:16 UTC, tatiana-dunice commented on controllers/auth/signup.js
> +      firstName: firstName.trim(),
better to create payload with all applicable(trimmed if need) values and use it futher -> in condition and for user creation

2022-07-29 07:16 UTC, tatiana-dunice commented on controllers/news/getAllNews.js
> +      include: 'user',
Do you need all user fields in the response? or some exact?

2022-07-29 07:16 UTC, tatiana-dunice commented on db/models/users.js
> +    const isCompare = await bcrypt.compare(password, this.password);
try to `return bcrypt.compare(password, this.password);`

2022-07-29 07:16 UTC, tatiana-dunice commented on routes/auth.js
> +const { authController } = require('../controllers');
imports should be before variables creation

2022-07-29 08:13 UTC, iSharovatov1 commented on db/models/users.js
> +      user.password = bcrypt.hashSync(user.password, bcrypt.genSaltSync(10), null);
user will get error "missed data"

2022-07-29 13:02 UTC, tatiana-dunice approved these changes

2022-07-29 13:02 UTC, merged